### ISSUE TITLE
KeyError on import

### ISSUE THREAD

**Issue by ghost** [vmassuchetto/beets-ydl#3]
I'm trying to use beets-ydl for tagging Bandcamp albums, but keep getting an error:

> $ beet ydl "https://androgynousbanana.bandcamp.com/album/year-of-the-flagon-2011-2014"
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/ydl.py", line 101, in ydl_func
    outer_class.youtubedl(lib, opts, arg)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/ydl.py", line 176, in youtubedl
    items = [x for x in lib.items('ydl:' + entry['id'])] + \
KeyError: 'id'

### Setup
OS: MacOS 10.13.6
beets version 1.4.8
Python version 3.7.2
plugins: bandcamp, edit, fetchart, fromfilename, ftintitle, hook, importadded, ydl

### Config
```yaml
plugins: edit ftintitle fromfilename importadded hook bandcamp fetchart ydl

import:
  copy: no         # Copy the file to our directory when importing?
  incremental: yes # Skip directories we already imported?
  write: yes        # Automatically write the file on library import / update?
  resume: yes      # Resume interrupted imports?
  log: beets.log   # Where should we write what we do?
  group_albums: yes

match:
  strong_rec_thresh: 0.1            # Any difference less than this is a strong recommendation
  preferred:                        # Put these at the top of recommendations
    countries: [US, GB|UK]          # My favorite music publishing countries
    media: [CD, Digital Media|File] # My favorite music sources
    original_year: yes              # entry year is close to entry original_year

bandcamp:
  split_artist_title: True

ydl:
  download: True
  split_files: True
  import: True
```
